### ISSUE TITLE
It just says "Invalid Channel"

### ISSUE THREAD

**Issue by Binary-Bytes** [BridgeSenseDev/Dank-Memer-Grinder#156] opened 2023-07-02 09:45 UTC
The GUI always says "`Invalid Channel`" even thought I'm putting the correct channel ID.
I'm on MacOS (M1) Ventura.

<img width="198" alt="Screenshot 2023-07-02 at 3 14 57 PM" src="https://github.com/BridgeSenseDev/Dank-Memer-Grinder/assets/88529771/ceeb3275-250c-40bc-a33d-5c4f6ceed4b0">

**Comment by BridgeSenseDev** [comment] 2023-09-04 01:22
Duplicate of #123

**Closed by BridgeSenseDev** 2023-09-04 01:22 UTC
