### ISSUE TITLE
Application isn't working

### ISSUE THREAD

**Issue by aditeyapatakoti** [BridgeSenseDev/Dank-Memer-Grinder#148] opened 2023-06-05 12:25 UTC
**Describe the bug**
I provided the token and channel ID and then chose the settings that I wanted for the grinder.  Once I was done I clicked on "Bot 1 Disabled (to enable it).  After doing so, the grinder indicated that it was an invalid channel.. I think that a server ID should be implemented into the grinder.  This will make it easier for the bot to go through the necessary steps to reach the channel it should be grinding in.

**OS:**
MacOS

**Comment by BridgeSenseDev** [comment] 2023-09-04 01:45
Duplicate of #123

**Closed by BridgeSenseDev** 2023-09-04 01:45 UTC
